DATA:
  BATCH_SIZE: 2 # 2 batch per GPU
MODEL:
  TYPE: 'PASSAT'
  OUTPUT: './Outputs/PASSAT'
  KERNEL_ALPHA: 0.05  # Sigma of Gauss Kernel
  PASSAT:
    EMBED_DIM: 48
    BACKBONE_DEPTHS: [2]
    BRANCH_DEPTHS: [[1], [2, 1]]
    LAMBDA_VELOCITY_VALUE: 10
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 1
  BASE_LR: 1e-3
  WARMUP_LR: 0
  MIN_LR: 3e-7
  AUTO_RESUME: True
  CLIP_GRAD: 1.0 
  ACCUMULATION_STEPS: 1